version: '3'

services:
  backend:
    build: ./backend
    container_name: cls-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=5000
      - DB_HOST=host.docker.internal
      # Use the following line instead if host.docker.internal doesn't work
      # - DB_HOST=172.17.0.1
      - DB_PORT=5432
      - DB_NAME=bank_admin_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - JWT_SECRET=your-secret-key-here
    networks:
      - cls-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: cls-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cls-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  store-frontend:
    build: ./store-frontend
    container_name: cls-store-frontend
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - cls-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  cls-network:
    driver: bridge
